name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-iseult:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0} # Required by conda setup or the environment won't activate properly

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environment.yml
        activate-environment: iseult
    - name: Report Package Versions
      run: |
        echo "===== Conda Info ======"
        conda info
        echo "===== Conda List ======"
        conda list
    - name: Run Tests
      run: python -m pytest

    # TODO: Add a linter here. flake8, ruff, and pylint are all options for linters
    # TODO: Add a formatter here. Black appears to be the best choice for formatter
    # - name: Lint with flake8
    #   run: |
    #     conda install flake8
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
